language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
sudo: false
os: linux

before_script:
  - npm install

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
